[package]
name = "a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.3.1"
quote = "1.0.23"
serde = "1.0.152"
serde_json = "1.0.93"
syn = "1.0.108"

